workflows:
  ios_build:
    name: iOS Release (no signing)

    triggers:
      - push

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      # ---------- LIMPIEZA COMPLETA ----------
      - name: Limpieza completa del proyecto
        script: |
          echo "Eliminando Pods antiguos..."
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.podspec
          rm -rf ios/Flutter/ephemeral
          rm -rf ios/build

          echo "Limpieza Flutter..."
          flutter clean
          flutter pub get

      # ---------- CREAR EL Runner.xcworkspace ----------
      - name: Configurar CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # ---------- BUILD ----------
      - name: Compilar iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/**
      - build/ios/iphoneos/*.app

    publishing:
      email:
        recipients:
          - "ftrejopaz@gmail.com"
