workflows:
  ios_release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        IOS_BUILD_TARGET: "ios"
    scripts:
      # -------------------------------------
      # CLEAN BUILD CACHE (Flutter + DerivedData + Pods)
      # -------------------------------------
      - name: Clean Flutter build
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData

      # -------------------------------------
      # INSTALL DEPENDENCIES
      # -------------------------------------
      - name: Install pub dependencies
        script: |
          flutter pub get

      - name: iOS pod install
        script: |
          cd ios
          pod install
          cd ..

      # -------------------------------------
      # BUILD iOS (RELEASE)
      # -------------------------------------
      - name: Build iOS release (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - build/**/Runner.app
      - build/**/Runner.ipa
    publishing:
      email:
        recipients:
          - "ftrejopaz@gmail.com"
        notify:
          success: true
          failure: true
