workflows:
  ios_release:
    name: iOS Release Clean Build
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        IOS_MIN_TARGET: "15.0"

    scripts:
      # 1) Limpieza completa de Flutter
      - name: Clean Flutter project
        script: |
          flutter clean
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/App.framework
          rm -rf ios/.symlinks
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf $HOME/.pub-cache
          flutter pub get

      # 2) Re-escribir el Podfile con el target mínimo
      - name: Update iOS deployment target
        script: |
          sed -i '' 's/platform :ios, .*/platform :ios, "15.0"/' ios/Podfile || true

      # 3) Regenerar proyecto iOS desde Flutter
      - name: Regenerate iOS folder (if needed)
        script: |
          flutter pub get
          flutter precache --ios

      # 4) Instalar Pods correctamente
      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..

      # 5) Build sin firmas
      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
