workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get
      
      - name: Install Pods
        script: |
          cd ios
          # Limpieza agresiva de caché de Pods
          rm -rf Pods
          rm Podfile.lock
          # Instalación de Pods
          pod install --repo-update
          cd ..
          
      - name: Build iOS
        script: |
          # Compilar sin firmar
          flutter build ios --release --no-codesign
          
      - name: Package IPA
        script: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          
    artifacts:
      - Runner.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - ftrejopaz@gmail.com