workflows:
  ios_release:
    name: iOS Release Build
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.15.2

    scripts:
      - name: Pre-build clean
        script: |
          echo "Running Flutter clean..."
          flutter clean

          echo "Removing iOS Pods..."
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks

          echo "Updating Cocoapods repo..."
          cd ios
          pod repo update
          cd ..

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS release (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app

    publishing:
      email:
        recipients:
          - "fer_trejopaz@gmail.com"