workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean and Get Packages
        script: |
          # Limpiar y descargar paquetes frescos
          flutter clean
          flutter pub get
      
      - name: Install Pods
        script: |
          # Entrar a carpeta iOS e instalar dependencias nativas
          cd ios
          # Limpieza preventiva de CocoaPods
          rm -rf Pods
          rm Podfile.lock
          # Instalación
          pod install --repo-update
          cd ..
          
      - name: Build iOS
        script: |
          # Compilar la app sin firmar (para Sideloadly)
          flutter build ios --release --no-codesign
          
      - name: Package IPA
        script: |
          # Empaquetar el resultado en un .ipa
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          
    artifacts:
      - Runner.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          # ¡PON AQUÍ TU EMAIL REAL!
          - tu_correo@ejemplo.com
